development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

production:
  host: localhost
  adapter: mysql
  database: peeoutside_production
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
