# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 21) do

  create_table "comments", :force => true do |t|
    t.column "entry_id",    :integer
    t.column "data",        :string
    t.column "created",     :datetime
    t.column "newsitem_id", :integer
    t.column "name",        :string
    t.column "location",    :string
  end

  add_index "comments", ["newsitem_id"], :name => "index_comments_on_newsitem_id"

  create_table "entries", :force => true do |t|
    t.column "title",           :string
    t.column "created",         :datetime
    t.column "approved",        :boolean,  :default => false
    t.column "thumb_small_id",  :integer
    t.column "thumb_medium_id", :integer
    t.column "upload_id",       :integer
    t.column "rating",          :float,    :default => 0.0
    t.column "number_ratings",  :integer,  :default => 0
  end

  add_index "entries", ["created"], :name => "index_entries_on_created"

  create_table "faqs", :force => true do |t|
    t.column "title",    :string
    t.column "body",     :text
    t.column "position", :integer
    t.column "created",  :datetime
  end

  add_index "faqs", ["created"], :name => "index_faqs_on_created"

  create_table "newsitems", :force => true do |t|
    t.column "title",    :string
    t.column "body",     :text
    t.column "created",  :datetime
    t.column "location", :string
  end

  add_index "newsitems", ["created"], :name => "index_newsitems_on_created"

  create_table "rating_records", :force => true do |t|
    t.column "cookie",   :string,  :default => "", :null => false
    t.column "entry_id", :integer
  end

  add_index "rating_records", ["cookie"], :name => "index_rating_records_on_cookie"
  add_index "rating_records", ["entry_id"], :name => "index_rating_records_on_entry_id"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "signups", :force => true do |t|
    t.column "first_name", :string
    t.column "last_name",  :string
    t.column "email",      :string
    t.column "pledged",    :boolean
    t.column "created",    :datetime
  end

  create_table "site_contacts", :force => true do |t|
    t.column "category", :string
    t.column "message",  :text
    t.column "email",    :string
    t.column "created",  :datetime
  end

  create_table "uploads", :force => true do |t|
    t.column "name",         :string
    t.column "data",         :binary
    t.column "content_type", :string
    t.column "created",      :datetime
    t.column "entry_id",     :integer,  :null => false
  end

  create_table "welcome_messages", :force => true do |t|
    t.column "body",    :text
    t.column "created", :datetime
  end

end
